const Constants = {
  MODAL_OVERLAY_OPACITY: 0.7,
  MODAL_CONTENT_WIDTH: 70,
  MODAL_CONTENT_HEIGHT: 70,
  MODAL_CLOSE_BUTTON_PLACEMENT: "top-right",
  MODAL_CLOSE_BUTTON_OFFSET_X: 16,
  MODAL_CLOSE_BUTTON_OFFSET_Y: 16,
};

export default Constants;
